name: Experiment1

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/experiment1.yml"
  workflow_dispatch:

jobs:
  experiment1:
    name: Experiment1
    runs-on: ubuntu-latest
    steps:
      - name: What is inside GITHUB_OUTPUT variable
        shell: bash
        run: |
          echo "$GITHUB_OUTPUT"

      - name: Is GITHUB_OUTPUT a file?
        shell: bash
        run: |
          file $GITHUB_OUTPUT

      - name: Lets put something to it
        id: put-foo
        shell: bash
        run: |
          echo "foo=bar" >> $GITHUB_OUTPUT

      - name: Lets see is it a file?
        shell: bash
        run: |
          file $GITHUB_OUTPUT

      - name: Can we read from it?
        shell: bash
        run: |
          cat $GITHUB_OUTPUT

      - name: Read output if it is not a file
        shell: bash
        run: |
          echo ${{ steps.put-foo.outputs.foo }}

      - name: Lets see what GITHUB_STEP_SUMMARY does
        shell: bash
        run: |
          echo ${{ steps.put-foo.outputs.foo }} >> $GITHUB_STEP_SUMMARY

      - name: Is GITHUB_STEP_SUMMARY a file?
        shell: bash
        run: |
          file $GITHUB_STEP_SUMMARY

      - name: Can we read from it?
        shell: bash
        run: |
          cat $GITHUB_STEP_SUMMARY

      - name: Can we 'echo' from it?
        shell: bash
        run: |
          echo $GITHUB_STEP_SUMMARY
