name: Experiment1

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/experiment1.yml"
  workflow_dispatch:

jobs:
  experiment1:
    name: Experiment1
    runs-on: ubuntu-latest
    steps:
      - name: What is inside GITHUB_OUTPUT variable
        shell: bash
        run: |
          echo "$GITHUB_OUTPUT"

      - name: Is GITHUB_OUTPUT a file?
        shell: bash
        run: |
          file $GITHUB_OUTPUT

      - name: Lets put something to it
        shell: bash
        run: |
          echo "foo=bar" >> $GITHUB_OUTPUT

      - name: Lets see is it a file?
        shell: bash
        run: |
          file $GITHUB_OUTPUT
